blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/z2f6qzc
    about: Join our discord server, to talk to us about this project & various directions it can take ! :D
